//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQUANLYBANHANGEntities : DbContext
    {
        public dbQUANLYBANHANGEntities()
            : base("name=dbQUANLYBANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATION> APPLICATIONS { get; set; }
        public virtual DbSet<GENDER> GENDERs { get; set; }
        public virtual DbSet<GENDER_TYPE> GENDER_TYPE { get; set; }
        public virtual DbSet<GROUP_USER> GROUP_USER { get; set; }
        public virtual DbSet<GROUP_USER_RELATIONSHIP_USER> GROUP_USER_RELATIONSHIP_USER { get; set; }
        public virtual DbSet<MENU_FORM> MENU_FORM { get; set; }
        public virtual DbSet<PARTY> PARTies { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbCHITIETHOADON> tbCHITIETHOADONs { get; set; }
        public virtual DbSet<tbDANHMUC> tbDANHMUCs { get; set; }
        public virtual DbSet<tbHOADON> tbHOADONs { get; set; }
        public virtual DbSet<tbKHANHHANG> tbKHANHHANGs { get; set; }
        public virtual DbSet<tbSANPHAM> tbSANPHAMs { get; set; }
    }
}
